<a href="https://colab.research.google.com/github/nguyenvang12003454/AIO_2025_Homework/blob/main/Daily_code_day_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - Gram Matrix in Style transfer

## Compute Gram Matrix from Feature Map

In [ ]:
import numpy as np

In [ ]:
def compute_gram_matrix(feature_map: np.ndarray) -> np.ndarray:
  C, H, W = feature_map.shape
  F = feature_map.reshape(C, H * W)
  return np.dot(F, F.T) / (H * W)

In [ ]:
# Feature map input
feature_map = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

In [ ]:
# Compute Gram Matrix
gram_matrix = compute_gram_matrix(feature_map)
print(gram_matrix)

[[  7.5  17.5  27.5]
 [ 17.5  43.5  69.5]
 [ 27.5  69.5 111.5]]


## Measure similarity between 2 images using Gram Matrix

In [ ]:
def compute_similarity(gram1: np.ndarray, gram2: np.ndarray) -> float:
  numerator = np.sum(gram1*gram2)
  denominator = np.sqrt(np.sum(gram1**2))*np.sqrt(np.sum(gram2**2))

  return numerator/denominator

In [ ]:
# Feature map input
feature_map1 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

feature_map2 = np.array([
    [[2, 4], [6, 8]],
    [[1, 3], [5, 7]],
    [[0, 2], [4, 6]]
])

In [ ]:
# Compute Gram Matrix
gram_matrix1 = compute_gram_matrix(feature_map1)
gram_matrix2 = compute_gram_matrix(feature_map2)

print(gram_matrix1)
print(gram_matrix2)

[[  7.5  17.5  27.5]
 [ 17.5  43.5  69.5]
 [ 27.5  69.5 111.5]]
[[30. 25. 20.]
 [25. 21. 17.]
 [20. 17. 14.]]


In [ ]:
# Compute similarity
similarity = compute_similarity(gram_matrix1, gram_matrix2)
print(similarity)

0.6741245785155123
